// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD63lzd1HH2QGct_mzGL2y40QOMIs4oiRM',
    appId: '1:977217360826:web:28130d1b127d5b57144383',
    messagingSenderId: '977217360826',
    projectId: 'twitch-e4e63',
    authDomain: 'twitch-e4e63.firebaseapp.com',
    storageBucket: 'twitch-e4e63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVtQzW-pDp5Rg-8fIUumkRu465PjlgzH4',
    appId: '1:977217360826:android:efb6fd234ad6ed08144383',
    messagingSenderId: '977217360826',
    projectId: 'twitch-e4e63',
    storageBucket: 'twitch-e4e63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvg6UgwD61n5AbrjNoE5zTAsM0h4PaKM0',
    appId: '1:977217360826:ios:a48bb8508f1ec000144383',
    messagingSenderId: '977217360826',
    projectId: 'twitch-e4e63',
    storageBucket: 'twitch-e4e63.firebasestorage.app',
    iosBundleId: 'com.example.twitchClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvg6UgwD61n5AbrjNoE5zTAsM0h4PaKM0',
    appId: '1:977217360826:ios:a48bb8508f1ec000144383',
    messagingSenderId: '977217360826',
    projectId: 'twitch-e4e63',
    storageBucket: 'twitch-e4e63.firebasestorage.app',
    iosBundleId: 'com.example.twitchClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD63lzd1HH2QGct_mzGL2y40QOMIs4oiRM',
    appId: '1:977217360826:web:42af879170fe2e82144383',
    messagingSenderId: '977217360826',
    projectId: 'twitch-e4e63',
    authDomain: 'twitch-e4e63.firebaseapp.com',
    storageBucket: 'twitch-e4e63.firebasestorage.app',
  );
}
