// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQORg-6Bg-KDwg6N1bCTCi8j1D7A_WmWo',
    appId: '1:902685381098:web:e8770a23a8b400af302293',
    messagingSenderId: '902685381098',
    projectId: 'twitch-78b5f',
    authDomain: 'twitch-78b5f.firebaseapp.com',
    storageBucket: 'twitch-78b5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt0ia6eBmTU1lGSyaXhKLqDob0ow6ZWKE',
    appId: '1:902685381098:android:78dba47d2ad02e05302293',
    messagingSenderId: '902685381098',
    projectId: 'twitch-78b5f',
    storageBucket: 'twitch-78b5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamzSQMQ9VgkD6uzyJeGoZZFvIDvXyVJg',
    appId: '1:902685381098:ios:c08146d8a39fa1a3302293',
    messagingSenderId: '902685381098',
    projectId: 'twitch-78b5f',
    storageBucket: 'twitch-78b5f.firebasestorage.app',
    iosBundleId: 'com.example.twitchClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDamzSQMQ9VgkD6uzyJeGoZZFvIDvXyVJg',
    appId: '1:902685381098:ios:c08146d8a39fa1a3302293',
    messagingSenderId: '902685381098',
    projectId: 'twitch-78b5f',
    storageBucket: 'twitch-78b5f.firebasestorage.app',
    iosBundleId: 'com.example.twitchClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQORg-6Bg-KDwg6N1bCTCi8j1D7A_WmWo',
    appId: '1:902685381098:web:bbb2a192e09eea09302293',
    messagingSenderId: '902685381098',
    projectId: 'twitch-78b5f',
    authDomain: 'twitch-78b5f.firebaseapp.com',
    storageBucket: 'twitch-78b5f.firebasestorage.app',
  );
}
